//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> orderID { get; set; }
        public string status { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
