//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptDetails
    {
        public int receiptID { get; set; }
        public string goodsID { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> total { get; set; }
    
        public virtual Goods Goods { get; set; }
        public virtual Receipt Receipt { get; set; }
    }
}
