//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public string ID { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
    
        public virtual ReceiptDetail ReceiptDetail { get; set; }
        public virtual ReceiptDetail ReceiptDetail1 { get; set; }
    }
}
